name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "1 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:      
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.wakatime.svg
          #token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
